### PR TITLE
added the footer and configured routing

### PR DESCRIPTION
**Pull request by obioraigboanusi**
I created all the components that might be required. 
Then, I connected the major components to the App.js component through React routing. 
 finally, I implemented the footer section.  
I added new features to the footer that would be really.

### CODE REVIEW

**Comment by obioraigboanusi** [comment]
footer
footer2

**Comment by obioraigboanusi** [comment]
Nice work.

**Review by MainaMary — COMMENTED** [review]
I have done the review. It is quite impressive. Please do the merging

**Review by Leonflixx — APPROVED** [review]

**Review by Leonflixx — APPROVED** [review]
awesome, heading in the right direction

**Comment by Ericawanja** [comment]
approved

**Pull request merged**
